### ISSUE TITLE
Tag a 1.0.0 release

### ISSUE THREAD

**Issue by meadsteve** [meadsteve/lagom#43]
The code is now used in a few projects and the interface seems stable. 

Needs:

- [ ] Decision on handling async construction https://github.com/meadsteve/lagom/issues/30
- [x] Decision on removing `suppress_error ` from the public interface (see https://github.com/meadsteve/lagom/pull/61 for where this could be done)

## Stretch goals
- [ ] better errors for infinite loops https://github.com/meadsteve/lagom/issues/60 
- [x] Env is available: https://github.com/meadsteve/lagom/issues/62
